version: '3'
services:
  app:
    build: .\backend
    restart: always
    container_name: app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mongodb://myuser:mypassword@mongodb
      - JWT_SECRET=verysecrectsfuff
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: myuser
      MONGO_INITDB_ROOT_PASSWORD: mypassword

volumes:
  mongodb_data:

networks:
  default:
    driver: bridge